name: Deploy Client

on:
  push:
    branches:
      - main
    paths:
      - 'live-demo/client/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Set up TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.41.0'
          install-binaryen: 'false'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Build WASM Binary
        run: |
          python live-demo/client/scripts/build_wasm.py \
            main.wasm \
            live-demo/client/static \
            live-demo/client/wasm/wasm.go

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './live-demo/client/static'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4